export const BookData = [
    {
        id: 0,
        book_name: "Harry Potter and the Philosopher's Stone",
        book_description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
    },
    {
        id: 1,
        book_name: "The Jungle Book",
        book_description: "Join Mowgli the Man-cub as he embarks on a dangerous journey through the jungle to escape the man-eating tiger Shere Khan. In his attempt to reach the Man-village, Mowgli discovers a whole new way of life when he meets the lovable bear, Baloo. The pair strike up a close friendship but will Mowgli reach the safety of the village before it is too late? Find out in this beautiful Disney storybook with an eye-catching lenticular cover.",
        book_url: "https://m.media-amazon.com/images/I/51cCdjGzuVL._SX364_BO1,204,203,200_.jpg",
        print_length: "200 pages",
        language: "English",
        author_name: "Rudyard Kipling",
        price: "340",
    },
    {
        id: 2,
        book_name: "Treasure Island",
        book_description: "Think of the high seas and of a buccaneer ship; of a wild seaman with a sea chest full of gold; of Long John Silver; of a buried treasure and of young Jim Hawkins, the boy with the treasure map the key to it all. This is the Treasure Island and if you don't think of all this, the pirates will hunt you down and when they find you, for find you they sure will, they will truss you and carry you back to their ship and just before they feed you to the sharks, as you walk the gangplank with a sword digging sharp and sure into your back, they will sing their one last song for you. “Fifteen men on the dead man's chest Yo-ho-ho and a bottle of rum!",
        book_url: "https://m.media-amazon.com/images/I/512c4l+AUrS._SX258_BO1,204,203,200_.jpg",
        print_length: "236 pages",
        language: "English",
        author_name: "R.L. Stevenson",
        price: "108",
    },
    {
        id: 3,
        book_name: "From the Earth to the Moon",
        book_description: "Written almost a century before the daring flights of the astronauts, Jules Verne’s prophetic novel of man’s race to the stars is a classic adventure tale enlivened by broad satire and scientific acumen. When the members of the elite Baltimore Gun Club find themselves lacking any urgent assignments at the close of the Civil War, their president, Impey Barbicane, proposes that they build a gun big enough to launch a rocket to the moon. But when Barbicane’s adversary places a huge wager that the project will fail and a daring volunteer elevates the mission to a “manned” flight, one man’s dream turns into an international space race. A story of rip-roaring action, humor, and wild imagination, From the Earth to the Moon is as uncanny in its accuracy and as filled with authentic detail and startling immediacy as Verne’s timeless masterpieces 20,000 Leagues Under the Sea and Around the World in Eighty Days.",
        book_url: "https://m.media-amazon.com/images/I/61r44FrbhLL._SX302_BO1,204,203,200_.jpg",
        print_length: "240 pages",
        language: "English",
        author_name: "Jules Verne",
        price: "202",
    },
    {
        id: 4,
        book_name: "Around The World In Eighty Days",
        book_description: "October 2, 1872, Reform Club, London. There is an article in the Daily Telegraph estimating that one can go round the world in eighty days. Phileas Fogg, a rich English gentleman, engages in a conversation with his partners at whist about the possibility of it. and this is what it leads to: “I will bet twenty thousand pounds against anyone who wishes, that I will make the tour of the world in eighty days or less; in nineteen hundred and twenty hours or a hundred and fifteen thousand two hundred minutes. Do you accept?”And soon, Fogg is on the 8.45 p.m. train to Italy from London with his French servant, Passe-partout. From trains to steamers to elephants, as Fogg travels across the four continents and different time zones, braving the unexpected, will he be able to circumnavigate the globe in eighty days? Will Phileas Fogg win the bet?Written during the Franco-Prussian War, Jules Verne’s Around the World in Eighty Days is a thrilling and lively adventure novel. Reimagined across various art forms, this unforgettable classic continues to challenge the spirit of adventure in its readers.",
        book_url: "https://m.media-amazon.com/images/I/510EvAURpTL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "248 pages",
        language: "English",
        author_name: "Jules Verne",
        price: "140",
    },
    {
        id: 5,
        book_name: "The Alchemist",
        book_description: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself.",
        book_url: "https://m.media-amazon.com/images/I/410llGwMZGL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "172 pages",
        language: "English",
        author_name: "Paulo Coelho",
        price: "286",
    },
    {
        id: 6,
        book_name: "To Kill a Mockingbird",
        book_description: "Shoot all the bluejays you want, if you can hit 'em, but remember it's a sin to kill a mockingbird.' A lawyer's advice to his children as he defends the real mockingbird of Harper Lee's classic novel - a black man falsely charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one man's struggle for justice. But the weight of history will only tolerate so much. To Kill a Mockingbird is a coming-of-age story, an anti-racist novel, a historical drama of the Great Depression and a sublime example of the Southern writing tradition.",
        book_url: "https://m.media-amazon.com/images/I/51Z9p5AecCL._SX307_BO1,204,203,200_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Harper Lee",
        price: "138",
    },
    {
        id: 7,
        book_name: "Do Epic Shit",
        book_description: "Ankur Warikoo is an entrepreneur and content creator whose deep, witty and brutally honest thoughts on success and failure, money and investing, self-awareness and personal relationships have made him one of India’s top personal brands. In his first book, Ankur puts together the key ideas that have fuelled his journey – one that began with him wanting to be a space engineer and ended with him creating content that has been seen and read by millions. His thoughts range from the importance of creating habits for long-term success to the foundations of money management, from embracing and accepting failure to the real truth about learning empathy. This is a book to be read, and reread, a book whose lines you will underline and think about again and again, a book you will give your family and friends and strangers. Ankur hopes for this book to become the most gifted book ever!",
        book_url: "https://m.media-amazon.com/images/I/41oYp387k8L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Ankur Warikoo",
        price: "312",
    },
    {
        id: 8,
        book_name: "Harry Potter and the Chamber of Secrets",
        book_description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as through turned to stone . Dobby's sinister predictions seem to be coming true.These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON .",
        book_url: "https://m.media-amazon.com/images/I/51yzj3H34aL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "224 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "310",
    },
    {
        id: 9,
        book_name: "The Subtle Art of Not Giving a F*ck",
        book_description: "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be “positive” all the time so that we can truly become better, happier people. For decades, we’ve been told that positive thinking is the key to a happy, rich life. “Fuck positivity,” Mark Manson says. “Let’s be honest, shit is fucked and we have to live with it.” In his wildly popular Internet blog, Manson doesn’t sugar-coat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mind-set that has infected",
        book_url: "https://m.media-amazon.com/images/I/511vJPN7p5L._SX331_BO1,204,203,200_.jpg",
        print_length: "384 pages",
        language: "English",
        author_name: "Mark Manson",
        price: "272",
    },
    {
        id: 10,
        book_name: "Ikigai",
        book_description: "THE INTERNATIONAL BESTSELLER We all have an ikigai. It's the Japanese word for a reason to live or a reason to jump out of bed in the morning. It's the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer. Finding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it. Do that, and you can make every single day of your life joyful and meaningful.",
        book_url: "https://m.media-amazon.com/images/I/51xwGSNX-EL._SX356_BO1,204,203,200_.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "Héctor García",
        price: "249",
    },
    {
        id: 11,
        book_name: "LINCHPIN",
        book_description: "In this compelling, accessible and purpose-filled book bestselling business author Seth Godin shows how you have the potential to make a big difference-and make yourself indispensable in the process-wherever you are.Why are some people easily outsourced, downsized, or freelanced into obscurity, while others have their pick of opportunities? In his most powerful book yet, Seth Godin argues that it's more essential than ever to become indispensable - to become a linchpin. Linchpins are the essential building blocks of great organizations: they invent, lead (regardless of title), connect others, make things happen, and create order out of chaos. They love their work and pour their best selves into it and turn each day into a kind of art - and, in today's world, they get the best jobs and the most freedom.Godin shows that the key to being indispensable is overcoming the fears that hold most of us back.",
        book_url: "https://m.media-amazon.com/images/I/51fGhgWMZKL._SX317_BO1,204,203,200_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Seth Godin",
        price: "294",
    },
    {
        id: 12,
        book_name: "Harry Potter and the Prisoner of Azkaban",
        book_description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves . But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss.",
        book_url: "https://m.media-amazon.com/images/I/51StPSSsneL._SX332_BO1,204,203,200_.jpg",
        print_length: "480 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
    },
    {
        id: 13,
        book_name: "Harry Potter and the Goblet of Fire",
        book_description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON.",
        book_url: "https://m.media-amazon.com/images/I/518TIrLNpOL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "439",
    },
    {
        id: 14,
        book_name: "Harry Potter and the Order of the Phoenix",
        book_description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time.",
        book_url: "https://m.media-amazon.com/images/I/511+ftLvTUL._SX332_BO1,204,203,200_.jpg",
        print_length: "816 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "475",
    },
    {
        id: 15,
        book_name: "Harry Potter and the Half Blood Prince",
        book_description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny.",
        book_url: "https://m.media-amazon.com/images/I/51XgBz54o3L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "560 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "429",
    },
    {
        id: 16,
        book_name: "Harry Potter and the Deathly Hallows",
        book_description: "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is now broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves, and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy.",
        book_url: "https://m.media-amazon.com/images/I/51cWQIhRUTL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "431",
    },
    {
        id: 17,
        book_name: "Think and Grow Rich",
        book_description: "Both poverty and riches are the offspring of thought.? since its first publication in 1937, think and Grow Rich has been considered the best self-help book in the world. A Bible for people seeking riches and prosperity, this book draws on the life stories of the wealthiest and most successful people of all time. Through this book Napoleon Hill will teach you what to do, and how to do it, to achieve lasting and unprecedented success. In this updated edition, the editors Bill and Ann Hartley have provided commentaries on many passages of the original text and examples of many more successful people, some of whom were inventors, senators, leaders of business and strategy, and even presidents of countries. Change your life as you learn to be ?the master of your fate and the Captain of your soul? through this powerful book.",
        book_url: "https://m.media-amazon.com/images/I/711xMzVPIuL._SL1500_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Napoleon Hill",
        price: "99",
    },
    {
        id: 18,
        book_name: "Rich Dad Poor Dad",
        book_description: "While there is a milestone to commemorate ― and a new section in the book on Why Milestones Are Important― preserving the integrity of the original content is testimony to the fact that this book has truly stood the test of time. The sidebars throughout the book (that were updated for the 20-year anniversary edition) have been updated again, but the core principles that parents and grandparents ― those who embraced Robert’s story and messages 25 years ago ― are sharing them with new generations who have found that its timeless wisdom and no-nonsense lessons can be applied to anyone’s life and their vision for a future that includes taking control of their finances. People of all cultures and countries celebrate milestones. We use them to measure time, mark progress, reflect on the lessons we’ve learned, and celebrate accomplishments… and they give meaning to our life’s journey. They are a way that we integrate past, present, and future… looking back at where we started, where we are today… and the promise of all that the future can hold. In the quarter century that has passed since Rich Dad Poor Dad was first published ― 25 years since April 8, 1997 ― so many things in our world have changed. But the one thing that has not changed is the pressing need for and the power of financial education. Money is still a mainstay of our lives,like it or not, and technology has brought both speed and innovations to the world of money. In an ever-changing world, we can all still get smarter when it comes to money… and learn as much as we can to secure our future..",
        book_url: "https://m.media-amazon.com/images/I/81BE7eeKzAL._SY466_.jpg",
        print_length: "336 pages",
        language: "English",
        author_name: "Robert Kiyosaki",
        price: "300",
    },
    {
        id: 19,
        book_name: "Reflections: Swami Vivekananda",
        book_description: "The grandest idea in the religion of the Vedanta is that we may reach the same goal by different paths; and these paths I have generalised into four, viz. those of work, love, psychology and knowledge. But you must, at the same time, remember that these divisions are not very marked and quite exclusive of each other. Each blends into the other. But according to the type which prevails, we name the divisions. It is not that you can find men who have no other faculty than that of work, nor that you can find men who are no more than devoted worshippers only, nor that there are men who have no more than mere knowledge. These divisions are made in accordance with the type or the tendency that may be seen to prevail in a man. We have found that, in the end, all these four paths converge and become one. All religions and all methods of work and worship lead us to one and the same goal.?Interactions ? Lectures And Discourses ? Vedanta, Bhakti And Culture ? Philosophy ? On India ? Man And Freedom ?Yoga ? Cities And Places ? Hymns ? Foreign Press.",
        book_url: "https://m.media-amazon.com/images/I/71agRE4WLRL._SY466_.jpg",
        print_length: "655 pages",
        language: "English",
        author_name: "Swami Vivekananda",
        price: "250",
    },
    {
    id: 20,
    book_name: "Don't Believe Everything You Think",
    book_description: "Discover how to conquer anxiety, self-doubt, and self-sabotage without depending on motivation or willpower. 'Don't Believe Everything You Think' uncovers the core of psychological suffering and offers insights to effortlessly shape the life you crave. Learn to detach from negativity, embrace love and joy, escape negative thought cycles, and tap into inner wisdom. The message is clear: anyone can attain peace, love, and fulfillment, irrespective of their history. It's not about rewiring your brain, but expanding your consciousness for lasting transformation. Within this book, delve into the core of emotional suffering and receive insights on effortlessly curating the life you aspire to.",
    book_url: "https://m.media-amazon.com/images/I/715qi-cIbML._SY466_.jpg",
    print_length: "128 pages",
    language: "English",
    author_name: "Joseph Nguyen",
    price: "230",
    },
    {
    id: 21,
    book_name: "The Power of Your Subconscious Mind",
    book_description: "This remarkable book by Dr. Joseph Murphy, one of the pioneering voices of affirmative thinking, will unlock for you the truly staggering powers of your subconscious mind. Combining time-honored spiritual wisdom with cutting edge scientific research, Dr. Murphy explains how the subconscious mind influences every single thing that you do and how, by understanding it and learning to control its incredible force, you can improve the quality of your daily life.Everything, from the promotion that you wanted and the raise you think you deserve, to overcoming phobias and bad habits and strengthening interpersonal relationships, the Power of Your Subconscious Mind will open a world of happiness, success, prosperity and peace for you. It will change your life and your world by changing your beliefs.",
    book_url: "https://m.media-amazon.com/images/I/41wVYuZMNTL._SY445_SX342_.jpg",
    print_length: "256 pages",
    language: "English",
    author_name: "Dr-Joseph-Murphy",
    price: "111",
    },
    {
    id: 22,
    book_name: "HOW TO WIN FRIENDS AND INFLUENCE PEOPLE ",
    book_description: "How to Win Friends and Influence People by bestselling author Dale Carnegie gives you time-tested advice and simple techniques on how to deal with people, understand them and get along with them. This book tells you how to: ? Improve your conversation skills ? Avoid arguments and win people over ? Make friends easily ? Become a people person A phenomenal success that has sold millions of copies worldwide, this book will change the way you approach relationships and better equip you to handle life?s situations.",
    book_url: "https://m.media-amazon.com/images/I/71JeBwdtGAL._SY466_.jpg",
    print_length: "296 pages",
    language: "English",
    author_name: "Dale Harbison Carnegie",
    price: "150",
    },
    {
     id: 23,
    book_name: "The 5 AM Club ",
    book_description: "Part manifesto for mastery, part playbook for genius-grade productivity and part companion for a life lived beautifully, the 5 am club is a work that will transform your life. Forever.Legendary leadership and elite performance expert Robin Sharma introduced The 5 AM Club concept over twenty years ago, based on a revolutionary morning routine that has helped his clients maximize their productivity, activate their best health and bulletproof their serenity in this age of overwhelming complexity.Now, in this life-changing book, handcrafted by the author over a rigorous four year period, you will discover the early-rising habit that has helped so many accomplish epic results while upgrading their happiness, helpfulness and feelings of aliveness.Through an enchanting?and often amusing?story about two struggling strangers who meet an eccentric tycoon who becomes their secret mentor, The 5 AM Club will walk you through:? How great geniuses, business titans and the world?s wisest people start their mornings to produce astonishing achievements? A little-known formula you can use instantly to wake up early feeling inspired, focused and flooded with a fiery drive to get the most out of each day ? A step-by-step method to protect the quietest hours of daybreak so you have time for exercise, self-renewal and personal growth? A neuroscience-based practice proven to help make it easy to rise while most people are sleeping, giving you precious time for yourself to think, express your creativity and begin the day peacefully instead of being rushed? ?Insider-only? tactics to defend your gifts, talents and dreams against digital distraction and trivial diversions so you enjoy fortune, influence and a magnificent impact on the world.",
    book_url: "https://m.media-amazon.com/images/I/618ZOX7UNNL._SY466_.jpg",
    print_length: "336 pages",
    language: "English",
    author_name: "Robin Sharma",
    price: "750",
    },
    {
            id: 24,
            book_name: "The Monk Who Sold His Ferrari",
            book_description: "A renowned inspirational fiction, The Monk Who Sold His Ferrari is a revealing story that offers the readers a simple yet profound way to live life. The plot of this story revolves around Julian Mantle, a lawyer who has made his fortune and name in the profession. A sudden heart-attack creates havoc in the successful lawyer?s life. Jolted by the sudden onset of the illness, his practice comes to a standstill. He ponders over material success being worth it all, renounces all of it and leaves for India. A visit to India about a spiritual awakening that opens up new vistas and Julian begins to view life in a different perspective. He decides to live his life once again but in a way that is much more fulfilling and meaningful than before. In the book, the reader goes through a spiritual journey and into a very old culture that has gathered much wisdom over the millennia. The book advocates about how to live happily, think deep and rightly, value time and relationships, be more disciplined, follow the heart?s call and live every moment of the life. Written in simple words, the book has turned out to be a bestseller and is more than just an endearing story. Through storytelling, Robin Sharma showcases the miracles and wonders of living a fulfilling life. In the process, the book introduces readers to enlightening yet simple principles that vouch to make life better, happier and more meaningful. A bestselling novel, what readers all over the globe appreciate about this book is its deft amalgam of the philosophies from both western and eastern worlds. The book has been followed by important personalities around the world. About the Author Robin Sharma, the bestselling author of 'The Monk Who Sold His Ferrari', first published in 1999, is an International Leadership Professional Guru who is credited with having written 15 books on leadership. He has been guiding people to live a better life, by drawing inspiration from his own life experiences. The Leader Who Had No Title, The Leader Who Had No Title, The Greatness Guide and The Saint and The Saint are among his best books. He heads the Sharma Leadership International Inc, a firm that trains people in leadership. A former litigation lawyer, Robin holds a law degree from Dalhousie Law School, Canada. This book along with The Greatness Guide has been among the world?s bestsellers and has been translated in as many as 70 languages all over the world.",
            book_url: "https://m.media-amazon.com/images/I/61pZyTuNDYL._SY466_.jpg",
            print_length: "198 pages",
            language: "English",
            author_name: "Robin Sharma",
            price: "300",
    },
    {
            id: 25,
            book_name: "As it is: Bhagavad-gita",
            book_description: "Bhagavad Gita in it's orignal form.",
            book_url: "https://m.media-amazon.com/images/I/51PstpFhznL._SY445_SX342_.jpg",
            print_length: "904 pages",
            language: "English",
            author_name: "A.C Bhaktivedanta Swami Prabhupada",
            price: "420",
    },
    {
            id: 26,
            book_name: "The Bhagavad Gita",
            book_description: "The Bhagwat Gita is the main sourcebook on yoga and is a concise summary of India's Vedic wisdom. Yet, remarkably, the setting for this classic spiritual text is an ancient Indian battlefield. In this interpretation of the Gita, the author explains that the essence of the Gita is the equanimity of mind, which is attained by transcending it because mind consciousness is myopic and only spiritual consciousness abounds in universal love and absolute knowledge. This best-selling and expanded edition of the most famous and popular of Indian scriptures contextualizes the book culturally and historically and explains the key concepts of Hindu religious thought and the technical vocabulary of yoga. Chapter introductions, notes and a glossary help readers understand the book's message better. Most importantly, the translation uses simple, clear language to impart the poetry, universality and timelessness of the Gita's teachings.",
            book_url: "https://m.media-amazon.com/images/I/71ouH7IhMVL._SY466_.jpg",
            print_length: "404 pages",
            language: "English",
            author_name: "R.R. Verma",
            price: "150",
    },
    {
            id: 27,
            book_name: "The Bhagwat Gita : Symphony of the Spirit ",
            book_description: "The Bhagwat Gita is the main sourcebook on yoga and is a concise summary of India's Vedic wisdom. Yet, remarkably, the setting for this classic spiritual text is an ancient Indian battlefield.In this interpretation of the Gita, the author explains that the essence of the Gita is the equanimity of mind, which is attained by transcending it because mind consciousness is myopic and only spiritual consciousness abounds in universal love and absolute knowledge. and expanded edition of the most famous and popular of Indian scriptures contextualizes the book culturally and historically and explains he key concepts of Hindu religious thought and the technical vocabulary of yoga. Chapter introductions, notes, and a glossary help readers understand the book's message better. Most importantly, the translation uses simple, clear language to impart the poetry, universality, and timelessness of the Gitas teachings.",
            book_url: "https://m.media-amazon.com/images/I/81jj54IP54L._SY466_.jpg",
            print_length: "520 pages",
            language: "Hindi",
            author_name: "R.R. Verma",
            price: "200",
    },
    {
            id: 28,
            book_name: "Shri Ramayana (Hindi) ",
            book_description: "The epic Ramayana is the story of the great Shri Rama, a god in human form— from his birth and childhood, his marriage to Sita, the daughter of King Janak, to the politics that led to his exile, the war he waged against Raavan, who had kidnapped his wife, and finally to his glorious victory and reinstatement as the ruler of Ayodhya.Valmiki's great epic, the Ramayana, is a must-read for all! Other titles by M I Rajasve: Ashtavakra Mahagita, Dashrath Nandan-Dashanan Gatha, Chanakya Charitam Aur Akhand Rashtriya Ekta, Ashwatthama ki Amar Mani, Ashwatthama ka Abhishap.The timeless epic enjoyed by people of all ages! Learn about the marriage of Rama and Sita and the trials faced by them. A tale of victory of good over evil!• One of the best translations by the celebrated mythology writer M I Rajasve.  Relive the glorious victory of Lord Rama over Raavan. A story of love, justice, war, and righteousness.",
            book_url: "https://m.media-amazon.com/images/I/810Y-6-ouCL._SY466_.jpg",
            print_length: "340 pages",
            language: "Hindi",
            author_name: "M I Rajasve",
            price: "290",
    },
    {
            id: 29,
            book_name: "Wisdom From The Ramayana: On Life and Relationships",
            book_description: "Wisdom From The Ramayana: On Life and Relationships offers insights from the ancient Hindu epic. Dive into the teachings of the Ramayana to discover timeless wisdom on love, loyalty, duty, and human values. Engaging storytelling that brings the epic to life Practical lessons applicable to modern-day life and relationships Deep exploration of character development and moral dilemmas A valuable resource for individuals seeking guidance and personal growth A beautifully designed hardcover edition that makes for a treasured addition to any library. ",
            book_url: "https://m.media-amazon.com/images/I/91fh1lxWjqL._SL1500_.jpg",
            print_length: "240 pages",
            language: "English",
            author_name: "Chaitanya Charan ",
            price: "150",
    },
    {
            id: 30,
            book_name: "Mahabharata: The Great Indian Epic",
            book_description: "In this gripping retelling of the ancient Indian epic, you will be transported into a world of warring kingdoms, magic, and divine intervention. Through the eyes of the Pandavas and Kauravas, witness a tale of love, loss, and redemption, as they battle for control of their kingdom and their own destinies. With vivid descriptions of the Kurukshetra War and political intrigue— read the Mahabharata like never before! • A massive epic. Explores concepts such as dharma, karma, and the nature of the self.• A rich and compelling work of literature. Continues to be a source of inspiration and guidance for millions of people around the world. Its themes of war, love, betrayal, and redemption are timeless. ",
            book_url: "https://m.media-amazon.com/images/I/816mUSrIprL._SY466_.jpg",
            print_length: "484 pages",
            language: "English",
            author_name: "Sudarshan ray ",
            price: "199",
    },
    {
            id: 31,
            book_name: "The Shiva Sutras ",
            book_description: "According to the legend, Sage Vasugupta received a divine revelation in a dream where Lord Shiva instructed him to seek out a specific stone near a serene stream. To his amazement, the stone turned over at his touch, revealing the sacred Shiva Sutras etched upon its surface. These profound sutras, reserved for those deemed worthy of divine grace, unravel the mysteries of our true nature and the illusory existence we inhabit. Ranjit Chaudhri has translated some important texts of Kashmir Shaivism from Sanskrit into English. These include 112 Meditations for Self Realization: The Vigyan Bhairava Tantra, The Shiva Sutras: Eternal Wisdom for Life, and Sounds of Liberation: The Spanda Karikas. Explore the divinity of Lord Shiva! The Shiva Sutras serve as a guiding light towards liberation from the illusion we perceive, leading us to ultimate reality. These sutras possess a transformative message that has the power to alleviate our suffering. By following the path illuminated by the Shiva Sutras, we can unveil a wondrous new realm of possibilities. The sutras offer profound insights that help us transcend the limitations of our current existence. Through the wisdom contained in the Shiva Sutras, we can embark on a journey of self-discovery and spiritual growth. ",
            book_url: "https://m.media-amazon.com/images/I/71RekQ752NL._SY466_.jpg",
            print_length: "144 pages",
            language: "English",
            author_name: "Ranjit Chaudhri",
            price: "159",
    },
    {
            id: 32,
            book_name: "Arthashastra by Kautilya - A Masterpiece on Economic Policies ",
            book_description: "Arthashastra is an ancient Indian text on statecraft and governance, written by Kautilya, a philosopher and statesman. This edition features the original text with a beautifully designed cover. With insights on politics, economics, and military strategy, this book remains relevant to modern-day readers interested in leadership and governance. Features the original text on statecraft and governance. Learn about the principles of economic management, trade, taxation, and wealth creation outlined in this influential treatise. Helps in gaining insights into the art of diplomacy and military strategy as elucidated by the revered scholar. The lessons and principles found in the Arthashastra continue to hold relevance in contemporary politics, governance, and strategic thinking. must-read for anyone interested in leadership and governance.",
            book_url: "https://m.media-amazon.com/images/I/71FF0AsDa+L._SY466_.jpg",
            print_length: "496 pages",
            language: "English",
            author_name: "Kautilya",
            price: "189",
    },
    {
            id: 33,
            book_name: "The Upanishads ",
            book_description: "A beautiful silk fabric hardbound pocked sized edition. The Upanishads, originally written during 5th century BC and first translated into English in early 19th century, are early philosophical texts of the Hindu religion and contain within them the tenets upon which the central philosophical concepts of the religion are based. A doctrine on Hindu thought and culture and perhaps the most important literature from ancient India, The Upanishads expound on principles like samsara, Brahman, atman, karma, dharma and moksha and form the core of Indian philosophy. Along with the Bhagavad Gita and the Brahmasutra, the Upanishads provide a foundation for the several later schools of Vedanta. This version is an English translation by Swami Paramananda as part of his mission to spread the Eastern teachings of Hinduism to the Western world. Paramananda was a Swami and one of the early Indian teachers who went to the United States to spread the Vedanta philosophy and religion. He was a mystic, a poet and an innovator in spiritual community living. Using his experience as a religious scholar, Paramananda sensitively and successfully translated the wisdom into the foremost of Western languages. Easy to understand and simply written, the thought behind this text is to know your self and follow the wisdom within the text to lead a wholesome and spiritually centered life.",
            book_url: "https://m.media-amazon.com/images/I/71yQBUcNMRL._SY466_.jpg",
            print_length: "184 pages",
            language: "English",
            author_name: "Swami Paramananda",
            price: "170",
    },
    {
            id: 34,
            book_name: "The Rudest Book Ever: Powerful Perspectives to Free Your Mind ",
            book_description: "YouTube megastar Shwetabh Gangwar, who has over 2.5 million followers on YouTube, is a professional problem-solver - and he's ace at it. For close to a decade, people from all over the world have contacted him with their troubles and he has worked them out for them. But be warned: Shwetabh has no desire to spare your feelings. He tells it like it is. What you will find in this straight-talking guide is: • How to make yourself incredibly stronger • How to develop complex thinking • How to move beyond good or bad and see people differently • How wanting happiness makes us miserable • How seeking approval from others kills the individual in you • How to find satisfaction in life And much more Sarcastic, straightforward and honest to the point of unintended rudeness, this book will make you rethink everything you have been taught.",
            book_url: "https://m.media-amazon.com/images/I/71iUJLYyM8L._SY466_.jpg",
            print_length: "240 pages",
            language: "English",
            author_name: "Shwetabh Gangwar",
            price: "300",
    },
    {
            id: 35,
            book_name: "Attitude Is Everything ",
            book_description: "IF YOU CAN DREAM IT, YOU CAN DO IT!Do you dread going to work? Do you feel tired, unhappy, weighed down? Have you given up on your dreams? The road to a happier, more successful life starts with your attitude--and your attitude is within your control.Whether your outlook is negative, positive or somewhere in between, Jeff Keller, motivational speaker and coach, will show you how to take control and unleash your hidden potential through three powerful steps:--THINK! Success begins in the mind. The power of attitude can change your destiny.--SPEAK! Watch your words. How you speak can propel you towards your goals.--ACT! Don't sit back. Take active steps to turn your dreams into reality.Soon, you will be energized and see new possibilities. You will be able to counter adversities and develop talents unique to you. Your relationships will improve, both at work and in your personal life. All you need is this step-by-step programme to change your attitude and your life!",
            book_url: "https://m.media-amazon.com/images/I/61go3pwTLYL._SY466_.jpg",
            print_length: "144 pages",
            language: "English",
            author_name: "Jeff Keller",
            price: "350",
    },
    {
            id: 36,
            book_name: "DORK DIARIES X 12 2020 ",
            book_description: "Dork Daires set of books in one place.",
            book_url: "https://m.media-amazon.com/images/I/61A4j+12sAL._SX342_SY445_.jpg",
            print_length: "1000 + pages",
            language: "English",
            author_name: "Rachel Renée Russell",
            price: "3000",
    },
    {
            id: 37,
            book_name: "Diary of Wimpy Kids Set of 13 Original Book ",
            book_description: " Diary of Wimpy Kid set of books in one place.",
            book_url: "https://m.media-amazon.com/images/I/817dIguWe9L._SY466_.jpg",
            print_length: "1000 + pages",
            language: "English",
            author_name: "Jeff Kinney",
            price: "2500",
    },
    {
            id: 38,
            book_name: "Dracula - A Timeless Novel ",
            book_description: " This is a beautiful hardbound edition of Dracula that comes with gilded edges and elegantly designed endpapers. Dracula is an epistolary novel, written as a collection of realistic but completely fictional diary entries, telegrams, letters, ship’s logs, and newspaper clippings, all of which add a level of detailed realism to Stoker’s story. At the time of its publication, Dracula was considered a ‘straightforward horror novel’ based on imaginary creations of supernatural life. Dracula has been assigned to many literary genres including vampire literature, horror fiction, the gothic novel, and invasion literature. The novel touches on themes such as the role of women in Victorian culture, sexual conventions, immigration, colonialism, and post-colonialism. Although Stoker did not invent the vampire, he defined its modern form through this novel.",
            book_url: "https://m.media-amazon.com/images/I/71l3BVfbrRL._SY466_.jpg",
            print_length: "440 pages",
            language: "English",
            author_name: "Edward Gorey",
            price: "430",
    },
    {
            id: 39,
            book_name: "YOU ONLY LIVE ONCE  ",
            book_description: " What if you ran away from your life today? Twenty years later, three people are looking for you. One is dying to meet you again.  The other wishes you had never met them ? The third wishes they could have met you at least once You are one person. Aren't you? But you are not the same person to each of them. Find the answers about your own life in this story about searching for love and discovering yourself. Join a broken but rising YouTube star Alara, a struggling but hopeful stand-up comedian Aarav, and a zany but zen beach shack owner Ricky. Together, take the journey to seek the truth behind the famous singer Elisha's disappearance somewhere by the deep sea in Goa. Will you be able to find Elisha? Or will you end up finding yourself?",
            book_url: "https://m.media-amazon.com/images/I/71dNsRuYL7L._SY466_.jpg",
            print_length: "240 pages",
            language: "English",
            author_name: "Stuti Changle",
            price: "130",
    },
    {
            id: 40,
            book_name: "Unusual Tales from Indian Mythology",
            book_description: "This gift edition features the greatest mythological stories retold by India' favourite author Sudha Murty. Filled with innumerable unusual legends of powerful gods and demons, alluring creatures and feisty women, the books in this collection are packed with arresting illustrations, captivating characters and magical worlds to keep every reader hooked. Read these enchanting narratives that will transport you to another time and fill you with a sense of wonder.",
            book_url: "https://m.media-amazon.com/images/I/81gAj78y6PL._SY466_.jpg",
            print_length: "990 pages",
            language: "English",
            author_name: "Sudha Murty",
            price: "730",
    },
    {
            id: 41,
            book_name: "Worry Less, Live More",
            book_description: "Do you struggle with negative thoughts and emotions that keep you from living the life you want? Do you feel stuck, hopeless, or overwhelmed by your problems? Do you wish you could break free from the cycle of worry and stress and enjoy more peace and happiness? If you answered yes to any of these questions, then this book is for you. In this book, you will learn how to use ACT therapy, a powerful and proven approach to help you cope with negative thoughts and emotions and live a more meaningful and fulfilling life. ACT stands for Acceptance and Commitment Therapy, a type of cognitive-behavioral therapy that combines mindfulness, acceptance, cognitive defusion, values, and committed action. ACT therapy can help you. Accept your thoughts and emotions without fighting or avoiding them. Detach yourself from your thoughts and see them as just words or images in your mind. Be more present and aware of the here and now, without judging or reacting to your experience. Identify and clarify your values, the things that matter most to you in life. Take action towards your goals and values, even when you face fear, doubt, or resistance. In this book, you will find practical exercises and examples to help you practice each of these skills and apply them to your own challenges and opportunities. You will also find personal stories and insights from the author, who discovered ACT therapy after struggling with anxiety and depression for years and transformed his life for the better. By reading this book and following the steps, you will be able to worry less, live more, and create the life you truly want. You will also gain access to additional resources and references for further learning and support.",
            book_url: "https://m.media-amazon.com/images/I/71AxeR8ZrsL._SY466_.jpg",
            print_length: "208 pages",
            language: "English",
            author_name: "Robern Morgan",
            price: "1600",
    },
    {
            id: 42,
            book_name: "William Shakespeare (Set of 15 Books)",
            book_description: "William Shakespeare is considered to be one of the most prominent playwrights of the world. Born on 23 April, 1564 in stratford-upon-avon, he is known as the greatest writer of the English language. His contribution in the domain of English language and literature is incomparable. His poetry and plays are the remarkable souvenirs of his genius. Shakespeare plays are divided into three categories: tragedies, histories and comedies. This set of 15 books includes Hamlet, the Tempest, Othello, the Merchant of Venice, the comedy of errors, Richard III, much ADO about nothing, Romeo & Juliet, Macbeth, Julius Caesar, as you Like It, king Lear, a Midsummer Night's dream, Antony and Cleopatra and twelfth night.",
            book_url: "https://m.media-amazon.com/images/I/71cpBSydJ0S._SY466_.jpg",
            print_length: "1920 pages",
            language: "English",
            author_name: "William Shakespeare ",
            price: "1232",
    },
    {
            id: 43,
            book_name: "Famous five and secret seven collection 7 books set",
            book_description: "Set of most books, Famous five and Secret Seven",
            book_url: "https://m.media-amazon.com/images/I/91N6J+wuZXL._SY466_.jpg",
            print_length: "1000 + pages",
            language: "English",
            author_name: "Enid Blyton ",
            price: "2103",
    },
    {
            id: 44,
            book_name: "Malory Towers Complete Box Set of 13 ",
            book_description: "Set of most famous books Malory Towers",
            book_url: "https://m.media-amazon.com/images/I/71Bl+huVmoL._SY466_.jpg",
            print_length: "1000 + pages",
            language: "English",
            author_name: "Enid Blyton ",
            price: "3376",
    },
    {
            id: 45,
            book_name: "The Secret + The Magic  ",
            book_description: "Set of most famous writer by Rhonda Byrne ",
            book_url: "https://m.media-amazon.com/images/I/41OIiA8VA+L.jpg",
            print_length: "500 pages",
            language: "English",
            author_name: "Rhonda Byrne ",
            price: "255",
    },
    {
            id: 46,
            book_name: " Best of Children’s Classic (Set of 5 Books)",
            book_description: "Discover a captivating collection of the five best works in children's literature, presented in a beautifully designed box set that is both a treasure for your library and an ideal gift. Join a young boy in a Sahara Desert crash landing, soar to Neverland with Peter Pan, explore the enchanting secret garden with Mary, journey to the magical city of Emeralds and encounter the Wizard of Oz, and befriend Sara, the imaginative little princess. These delightful and enthralling tales of adventure have stood the test of time, remaining beloved favorites that ignite the imagination and capture the hearts of readers of all ages. ",
            book_url: "https://m.media-amazon.com/images/I/71OeSw46tCL._SY466_.jpg",
            print_length: "936 pages",
            language: "English",
            author_name: "Frances Eliza Hodgson Burnett",
            price: "999",
    },
    {
            id: 47,
            book_name: "DEMONSLAYER MANAGA VOLUMES 1-23 (Kimetsu no Yaiba)",
            book_description: "In Taisho-era Japan, kindhearted Tanjiro Kamado makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. His little sister Nezuko is the only survivor, but she has been transformed into a demon herself! Tanjiro sets out on a dangerous journey to find a way to return his sister to normal and destroy the demon who ruined his life. ",
            book_url: "https://m.media-amazon.com/images/I/81t+KCcpkvL._SX679_.jpg",
            print_length: "4496 pages",
            language: "English",
            author_name: "Koyoharo Gotouge",
            price: "4500",
    },
    {
            id: 48,
            book_name: "Death Note Manga Box Set Vols 1-13",
            book_description: "Set of books for Manga Death Note ",
            book_url: "https://m.media-amazon.com/images/I/71teEs2FRpL._SY466_.jpg",
            print_length: "2496 pages",
            language: "English",
            author_name: "Tsugumi Ohba",
            price: "5545",
    },
    {
            id: 49,
            book_name: "Tokyo Ghoul Manga Re Boxset: Includes vols. 1-1",
            book_description: "Set of books for Manga Tokyo Ghoul ",
            book_url: "https://m.media-amazon.com/images/I/71iY7MvElDL._SY466_.jpg",
            print_length: "3766 pages",
            language: "English",
            author_name: "Sui Ishida",
            price: "7560",
    },
    {
            id: 50,
            book_name: "Jujutsu Kaisen: The Official Anime Guide: Season 1",
            book_description: "The official companion to the first season of the hugely popular Jujutsu Kaisen anime. Enter the world of jujutsu sorcerers and cursed spirits with Jujutsu Kaisen: The Official Anime Guide: Season 1. Based on the hugely popular manga series by Gege Akutami, this guide to the Jujutsu Kaisen anime will provide readers with everything they wanted to know about the making of the action-packed series. Discover all the behind-the-scenes details as the anime production team discusses the painstaking work that went into translating the pages of the best-selling manga to animation. Featuring concept art, original storyboards, character design sketches, exclusive interviews, and commentary from the voice actors, this book also includes two double-sided posters and is the ultimate look into the creation of the first season of Jujutsu Kaisen! ",
            book_url: "https://m.media-amazon.com/images/I/815Hq6BC0hL._SY466_.jpg",
            print_length: "168 pages",
            language: "English",
            author_name: "Gege Akutami",
            price: "1122",
    },
    {
            id: 51,
            book_name: "MANGA One Piece Books Set Vol 1: Volumes 1-23",
            book_description: "One Piece Set of books ",
            book_url: "https://m.media-amazon.com/images/I/71yD-i4HyEL._SX679_.jpg",
            print_length: "4840 pages",
            language: "English",
            author_name: "Eiichiro Oda",
            price: "3799",
    },
    {
            id: 52,
            book_name: "Spy X Family Manga Volumes 1 - 8",
            book_description: "Spy X Family Manga Volumes 1 - 8 ",
            book_url: "https://m.media-amazon.com/images/I/811v269UbxL._SY466_.jpg",
            print_length: " 1825  pages",
            language: "English",
            author_name: "Tatsuya Endo",
            price: "1070",
    },
    {
            id: 53,
            book_name: "Chainsaw Man Box Set: Includes volumes 1-11",
            book_description: "Broke young man + chainsaw demon = Chainsaw Man! Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man! The rip-roaring first arc of Chainsaw Man, all in one jaw-dropping box set! This box set contains the first 11 volumes of the global hit Chainsaw Man as well as an exclusive double-sided full-color poster.",
            book_url: "https://m.media-amazon.com/images/I/81u8igOscKL._SY466_.jpg",
            print_length: " 2112  pages",
            language: "English",
            author_name: "Tatsuki Fujimoto",
            price: "5439",
    },
    {
            id: 54,
            book_name: "1984 (Marathi)",
            book_description: "Published in the summer of 1949, George Orwell’s Nineteen Eighty-Four is one of the most definitive texts of modern literature. Set in Oceania, one of the three inter-continental superstates that divided the world among themselves after a global war, Orwell’s masterful critique of the political structures of the time, works itself out through the story of Winston Smith, a man caught in the webs of a dystopian future, and his clandestine love affair with Julia, a young woman he meets during the course of his work for the government. As much as it is an entertaining read, Nineteen-Eighty-Four is also a brilliant, and more importantly, a timeless satirical attack on the social and political structures of the world.",
            book_url: "https://m.media-amazon.com/images/I/81CJIMkHCsL._SY466_.jpg",
            print_length: "304 pages",
            language: "Marathi",
            author_name: "George Orwell",
            price: "150",
    },
    {
            id: 55,
            book_name: "Yayati (Marathi) ",
            book_description: "Yayati? is one of the most popular and respected novels in Marathi Literature. Revolving around the legendary love story of Yayati and Devyani, characters from Mahabharata, this novel is regarded as one of the best literary masterpieces ever written. The brilliant narration and metaphors used in the novel add to the poetic appeal. Written by V.S Kandekar, it is a story that keeps the reader glued till the end. It is published by Mehta Publishing House in 1959. This novel has won the Jnanpith Award which is India?s highest literary recognition. Devyani and Sharmishtha are friends and jealousy creates tension among them. Both fall in love with Yayati, a handsome prince who is full of bravery and has won accolades which even made Indra hold him in high esteem. However, due to some tragic events, Yayati gets married to Devyani and Sharmishta comes with Devyani as her maid. During her stay with Devyani, Sharmishta and Yayati fall in love with each other and create a bond that is inseparable. This disrupts the married life of Yayati and Devayani. Yayati then falls in the never ending trap of lust and breaks all moral and ethical rules. Will Yayati ever come out out this lust-trap? Will his son sacrifice his youth for the enjoyment of his father? Can Devyani stop Yayati from this self-demolition? What does fate hold for Sharmishta? Can her love save Yayati? This novel is a beautiful love story written with the highest literary standards. About the author Vishnu Sakharam Khandekar is one of the most famous Marathi authors who is known for his distinctive style and literary mastery. He began his career as an actor and was a part of a few plays, before settling down as a school teacher. This is where his writing talent was born and during his teaching career, he wrote several novels and plays. In 1998, he was conferred an honorary degree of D.Litt. by Shivaji University, Kolhapur and was honoured with several awards like the Padma Bhushan award. He was the first Marathi writer to win the prestigious Jnanpith Award, the country's highest literary recognition. The book, 'Yayati? is a fascinating novel and is easily available online for convenient shopping. You can bag this book from A today by following a few easy steps.",
            book_url: "https://m.media-amazon.com/images/I/619joW8umEL._SY466_.jpg",
            print_length: "432 pages",
            language: "Marathi",
            author_name: " V.S Kandekar",
            price: "230",
    },
    {
            id: 56,
            book_name: "Sukhacha Shodh (Marathi) ",
            book_description: "What is human life? It is a union of three beautiful feelings. The first is our own happiness and progress. The second felling is towards our family, the obligations, the indebtness. One has to try to repay it to the best of his/her ability. The third is the unseen flow, to help the society progress, the society of which we are members. Ones life can be said fulfilled only when the indebtedness of ourselves, that of the family and of the society is satisfied at the same time. If there is no conflict between these three then we can say that the person is successful in his life. V. S. Khandekar's book reveals these secrets of human life in his novel. There are many characters in this novel Of them, Anand believes only in sacrifice, the traditional belief; Appa and Bhayya are those incompetent people who shade off their responsiblities and justify themselves by making a single person shoulder it. Manik is hopeless, literate girl but has always failed in recognising a good mind, Usha is yet another character who has been aloof, never expressing feelings, good or bad. What are these characters eilling us? They tell us that following the customs and traditions blindlessly is harmful not only to the person following them but also to the society at large. It was in 1939 that the author stated his views as follows, 'when we talk about the values in a man's life then sacrifice is alway highly regarded than enduring. But the sacrifice should always be for a noble cause.' Do not you think that this view is true even today?",
            book_url: "https://m.media-amazon.com/images/I/51UlrPXj2gL._SY466_.jpg",
            print_length: "112 pages",
            language: "Marathi",
            author_name: " V.S Kandekar",
            price: "120",
    },
    {
            id: 57,
            book_name: "Bakula ",
            book_description: "Every time, she sent him a letter, she sent a small flower of 'bakul' for him, without fail. Her letter always brought back some special memories for Shridhar. He used to get lost in the memories with the small flower in his hand. The flower represented her. Her mild manners, her simplicity, the fragrance around her, and the chastity in her eyes along with the love every single tender thing was present in the flower. Her personality was devoid of ego. He had collected each flower from her letter. He had stored all those flowers in a small bag. Every day, he kept the bag beneath his pillow. Every letter brought a new hope for him, saying that the flower will be a lifelong partner. Sudha Murthy, has pictured this very sensitively.",
            book_url: "https://m.media-amazon.com/images/I/61Cg733mtYL._SY466_.jpg",
            print_length: "148 pages",
            language: "Marathi",
            author_name: "Sudha Murty",
            price: "110",
    },
    {
            id: 58,
            book_name: "Shyamchi Aai ",
            book_description: "श्यामची आई हे पांडुरंग सदाशिव साने यांनी लिहिलेली मराठी आत्मकहाणी आहे. नाशिकच्या कारागृहात असताना फेब्रुवारी ९, इ.स. १९३३ रोजी त्यांनी या पुस्तकाच्या लिखाणास प्रारंभ केला. या पुस्तकाच्या ३ लाखांपेक्षा अधिक प्रती खपल्या आहेत. इ.स. १९५३ साली या पुस्तकावर आधारित असलेला 'श्यामची आई' याच नावाचा चित्रपटदेखील पडद्यांवर झळकला. प्रल्हाद केशव अत्रे यांनी या चित्रपटाचे दिग्दर्शन केले होते. मातेबद्दल असणारे प्रेम, भक्ति व कृतज्ञता यांच्या अपार भावना ’श्यामची आई’ या पुस्तकात मांडलेल्या आहेत. नाशिकच्या तुरुंगात साने गुरुजींनी ही कथा ९ फेब्रुवारी, इ.स. १९३३ रोजी लिहावयास सुरुवात केली आणि १३ फेब्रुवारी, इ.स. १९३३ रोजी पहाटे त्या संपविल्या.",
            book_url: "https://m.media-amazon.com/images/I/71SWAytWstL._SY466_.jpg",
            print_length: "215 pages",
            language: "Marathi",
            author_name: "Sane Guruji",
            price: "110",
    },
    {
            id: 59,
            book_name: "Gulmohar ",
            book_description: "THE NAME SUGGESTS THE FOUNDATION OF THE STORIES. THIS IS AN EXCLUSIVE COLLECTION OF ONLY 8 STORIES BASED ON SOME WHIMSICAL CHARACTERS. EVERY MAIN CHARACTER IN ALL THESE STORIES HAS ONE THING IN COMMON. IN A TRUE SENSE, THEY ARE NOT WHIMSICAL; ACTUALLY THEY HAVE SET THEIR OWN DOCTRINES AND HAVE STUCK TO THEM, NO MATTER WHATEVER HAPPENS. IN ONE OF THE STORIES, THE HERO DIES JUST BECAUSE OF HIS DOCTRINES. THE OTHER STORY IS BASED ON THE MENTALITY OF BEING LAME; IT PROVES THAT MANY A TIMES THOSE WHO ARE PHYSICALLY DISABLED ARE MORE FIRM THAN THOSE WHO ARE PHYSICALLY CAPABLE OF DOING EVERYTHING BUT HAVE A LAME AND LIMP MIND. ONE STORY IS BASED ON THE INSECURITY; HERE THE HEROINE WHO HAD REFUSED SOMEONE WHOM SHE LOVED SO MUCH COMES INTO CONTACT WITH HIM AGAIN. SHE FEELS THAT HE WILL BLACKMAIL HER BUT FAILS TO UNDERSTAND HIM, AT THE END, THOUGH VERY BEAUTIFUL, HER INSECURE MIND SHOWS ITS UGLINESS. EACH AND EVERY STORY HAS SOME SPLENDID FELLING OR OTHER TO SHARE WITH US, TO REVEAL THE VASTNESS AND THE INSULARITY OF THE MIND.",
            book_url: "https://m.media-amazon.com/images/I/612Tc1Zdc7L._SY466_.jpg",
            print_length: "128 pages",
            language: "Marathi",
            author_name: "V.P. Kale",
            price: "124",
    },
    {
            id: 60,
            book_name: "Hi Vaat Ekatichi",
            book_description: "Hi Vaat Ekatichi ",
            book_url: "https://m.media-amazon.com/images/I/6188CCt4P7L._SY466_.jpg",
            print_length: "164 pages",
            language: "Marathi",
            author_name: "V.P. Kale",
            price: "150",
    },
    {
            id: 61,
            book_name: "Shri Gurucharitra (Big) (Marathi)",
            book_description: "Shri Gurucharitra (Big) (Marathi) ",
            book_url: "https://m.media-amazon.com/images/I/91eoAVV3tHL._SX679_.jpg",
            print_length: "688 pages",
            language: "Marathi",
            author_name: "RamChandra Krushna Kamat",
            price: "509",
    },
    {
            id: 62,
            book_name: "Coding: 6 BOOKS IN 1",
            book_description: "Coding: 6 BOOKS IN 1 : Linux For Beginners  PYTHON (2) - SQL - HTML  C++ PROGRAMMING (part of : Computer Pogramming ( 35+ books )) ",
            book_url: "https://m.media-amazon.com/images/I/81Xp0a6+oHL._SY466_.jpg",
            print_length: "1000 +pages",
            language: "English",
            author_name: "Michael Clark",
            price: "1023",
    },
    {
            id: 63,
            book_name: "TOPPERSNOTES GATE Exam",
            book_description: "ToppersNotes GATE exam book for Computer Science & Information Technology engineering helps aspirants to crack this prestigious exam with minimum preparation. GATE Computer Science & Information Technology Engineering exam holds high importance in the life of a person. This will bring you onboard with mainstream so that you don't leave anything. The notes cover every aptitude for gate, tricks, shortcuts, and methods to solve the problem within the shortest span of time. ",
            book_url: "https://m.media-amazon.com/images/I/61Tl5qpUJKL._SY466_.jpg",
            print_length: "2000 pages",
            language: "English",
            author_name: "TopperNotes",
            price: "2,456",
    },
    {
            id: 64,
            book_name: "Quick Start Guide",
            book_description: "Large Language Models (LLMs) like ChatGPT are demonstrating breathtaking capabilities, but their size and complexity have deterred many practitioners from applying them. In Quick Start Guide to Large Language Models, pioneering data scientist and AI entrepreneur Sinan Ozdemir clears away those obstacles and provides a guide to working with, integrating, and deploying LLMs to solve practical problems. Ozdemir brings together all you need to get started, even if you have no direct experience with LLMs: step-by-step instructions, best practices, real-world case studies, hands-on exercises, and more. Along the way, he shares insights into LLMs' inner workings to help you optimize model choice, data formats, parameters, and performance. You'll find even more resources on the companion website, including sample datasets and code for working with open- and closed-source LLMs such as those from OpenAI (GPT-4 and ChatGPT), Google (BERT, T5, and Bard), EleutherAI (GPT-J and GPT-Neo), Cohere (the Command family), and Meta (BART and the LLaMA family). Learn key concepts: pre-training, transfer learning, fine-tuning, attention, embeddings, tokenization, and more Use APIs and Python to fine-tune and customize LLMs for your requirements Build a complete neural/semantic information retrieval system and attach to conversational LLMs for retrieval-augmented generation Master advanced prompt engineering techniques like output structuring, chain-ofthought, and semantic few-shot prompting Customize LLM embeddings to build a complete recommendation engine from scratch with user data Construct and fine-tune multimodal Transformer architectures using opensource LLMs Align LLMs using Reinforcement Learning from Human and AI Feedback (RLHF/RLAIF) Deploy prompts and custom fine-tuned LLMs to the cloud with scalability and evaluation pipelines in mind ",
            book_url: "https://m.media-amazon.com/images/I/61mEgqic90L._SY466_.jpg",
            print_length: "256 pages",
            language: "English",
            author_name: "Sinan Ozdemir",
            price: "3,745",
    },
    {
            id: 65,
            book_name: "Counting the Cost",
            book_description: "Jill and Derick knew a normal life wasn't possible for them. As a star on the popular TLC reality show 19 Kids and Counting, Jill grew up in front of viewers who were fascinated by her family's way of life. She was the responsible, second daughter of Jim Bob and Michelle's nineteen kids; always with a baby on her hip and happy to wear the modest ankle-length dresses with throat-high necklines. She didn't protest the strict model of patriarchy that her family followed, which declares that men are superior, that women are expected to be wives and mothers and are discouraged from attaining a higher education, and that parental authority over their children continues well into adulthood, even once they are married. But as Jill got older, married Derick, and they embarked on their own lives, the red flags became too obvious to ignore. For as long as they could, Jill and Derick tried to be obedient family members—they weren’t willing to rock the boat. But now they’re raising a family of their own, and they’re done with the secrets. Thanks to time, tears, therapy, and blessings from God, they have the strength to share their journey. Theirs is a remarkable story of the power of the truth and is a moving example of how to find healing through honesty.",
            book_url: "https://m.media-amazon.com/images/I/41zDPnwaOYL._SY445_SX342_.jpg",
            print_length: "288 pages",
            language: "English",
            author_name: "Jill Duggar",
            price: "1,226",
    },
    {
            id: 66,
            book_name: "Eye",
            book_description: "From working on visual development for the anime film Promare, to production of the end credits for Cyberpunk: Edgerunners and more, Yoneyama Mai is active in the world of anime and illustration. This edition features a complete archive of the illustrations that make you feel the flow of emotions and movement that Yoneyama Mai is known for.  This is the first collection of original works by Yoneyama Mai, who has more than one million followers on Twitter and is getting attention from both animators and creators! Enjoy the vivid colors and delicate details in Yoneyama’s work. ",
            book_url: "https://m.media-amazon.com/images/I/81E1dMGGFZL._SY466_.jpg",
            print_length: "272 pages",
            language: "English",
            author_name: "Yoneyama Mai",
            price: "3,172",
    },
    {
        id: 67,
        book_name: "Polymeric Materials ",
        book_description: "Modern electronic products are manufactured at a finer scale and with more precision than ever before. This places increasing demand on the proper use and management of high-performance polymers to create reliable, rapidly-operating semiconductor products. Understanding the physical properties and viscoelasticity analysis of resins is essential for engineers and researchers to perfect and deploy these polymers in electronics contexts. Polymeric Materials for Electronic Packaging is designed to meet this specific need with a thorough introduction to these materials and their production. It provides the tools engineers need to reduce processing times and increase durability in their semiconductor packages and products. Translated from the Japanese original and offering in-depth analysis from a global-leading expert, this promises to be an indispensable volume. ",
        book_url: "https://m.media-amazon.com/images/I/81td8ZaOx2L._SY466_.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "Shozo Nakamura",
        price: "10,271",
    },
    {
        id: 68,
        book_name: "Ugly Love",
        book_description: "#1 New York Times bestselling author Colleen Hoover returns with a new heart-wrenching love story. When Tate Collins meets airline pilot Miles Archer, she doesn't think it's love at first sight. They wouldn't even go so far as to consider themselves friends. The only thing Tate and Miles have in common is an undeniable mutual attraction. Once their desires are out in the open, they realize they have the perfect set-up. He doesn't want love, she doesn't have time for love, so that just leaves the sex. Their arrangement could be surprisingly seamless, as long as Tate can stick to the only two rules Miles has for her. Never ask about the past. Don't expect a future.",
        book_url: "https://m.media-amazon.com/images/I/81AUBgVLyyL._SY466_.jpg",
        print_length: "336 pages",
        language: "English",
        author_name: "Colleen Hoover ",
        price: "309",
    },
    {
        id: 69,
        book_name: "A Good Girl's Guide",
        book_description: "A stunning collectors edition of the first book in this bestselling, award-winning series, presented in a beautiful hardback format with an introductory letter from the author, sprayed edges and a ribbon bookmark. The case is closed. Five years ago, schoolgirl Andie Bell was murdered by Sal Singh. The police know he did it. Everyone in town knows he did it. But having grown up in the same small town that was consumed by the crime, Pippa Fitz-Amobi isn't so sure. When she chooses the case as the topic for her final project, she starts to uncover secrets that someone in town desperately wants to stay hidden. And if the real killer is still out there, how far will they go to keep Pip from the truth … ? Perfect for fans of One of Us Is Lying, Gone Girl, We Were Liars and Riverdale.",
        book_url: "https://m.media-amazon.com/images/I/71-m9u7PCwL._SY466_.jpg",
        print_length: "448 pages",
        language: "English",
        author_name: "Holly Jackson ",
        price: "324",
    },
    {
        id: 70,
        book_name: "The Midnight Library",
        book_description: "When Nora Seed finds herself in the Midnight Library, she has a chance to make things right. Up until now, her life has been full of misery and regret. She feels she has let everyone down, including herself. But things are about to change. The books in the Midnight Library enable Nora to live as if she had done things differently. With the help of an old friend, she can now undo every one of her regrets as she tries to work out her perfect life. But things aren't always what she imagined they'd be, and soon her choices place the library and herself in extreme danger. Before time runs out, she must answer the ultimate question: what is the best way to live?",
        book_url: "https://m.media-amazon.com/images/I/71qsovx-x6L._SY466_.jpg",
        print_length: "304 pages",
        language: "English",
        author_name: "Matt Haig ",
        price: "425",
    },
    {
        id: 71,
        book_name: "November 9",
        book_description: "Beloved #1 New York Times bestselling author Colleen Hoover returns with an unforgettable love story between a writer and his unexpected muse. Fallon meets Ben, an aspiring novelist, the day before her scheduled cross-country move. Their untimely attraction leads them to spend Fallon?s last day in L.A. together, and her eventful life becomes the creative inspiration Ben has always sought for his novel. Over time and amidst the various relationships and tribulations of their own separate lives, they continue to meet on the same date every year. Until one day Fallon becomes unsure if Ben has been telling her the truth or fabricating a perfect reality for the sake of the ultimate plot twist. Can Ben?s relationship with Fallon?and simultaneously his novel?be consid-ered a love story if it ends in heartbreak?",
        book_url: "https://m.media-amazon.com/images/I/71RBpTJkKaL._SY466_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Colleen Hoover ",
        price: "309",
    }
    
]


                                                                                                                                                                                        
                                                                                                                                                                                           